CPARAMS=-ffreestanding -O0 -Wall -Wextra -no-pie -fno-pic
.RECIPEPREFIX = >

all:
> @mkdir ../../build -p
> @mkdir ../../build/etc -p

> @echo Compiling etc/appman.c ...
        
> @i686-linux-gnu-gcc -c appman.c $(CPARAMS) -o ../../build/etc/appman.o 
            
> @echo etc branch done.
    