CPARAMS=-ffreestanding -O2 -Wall -Wextra -no-pie
.RECIPEPREFIX = >

all:
> @mkdir ../../build -p
> @mkdir ../../build/application_terminal -p

> @echo Compiling application_terminal/main.c ...
        
> @i686-linux-gnu-gcc -c main.c $(CPARAMS) -o ../../build/application_terminal/main.o 
            
> @echo application_terminal branch done.
    