CPARAMS=-ffreestanding -O2 -Wall -Wextra -no-pie -g
.RECIPEPREFIX = >

all:
> @mkdir ../../build -p
> @mkdir ../../build/application_bootscreen -p

> @echo Compiling application_bootscreen/main.c ...
        
> @i686-linux-gnu-gcc -c main.c $(CPARAMS) -o ../../build/application_bootscreen/main.o 
            
> @echo application_bootscreen branch done.
    