CPARAMS=-ffreestanding -O0 -Wall -Wextra -no-pie -fno-pic
.RECIPEPREFIX = >

all:
> @mkdir ../../build -p
> @mkdir ../../build/applications_enableints -p

> @echo Compiling applications_enableints/main.c ...
        
> @i686-linux-gnu-gcc -c main.c $(CPARAMS) -o ../../build/applications_enableints/main.o 
            
> @echo applications_enableints branch done.
    