CPARAMS=-ffreestanding -O2 -Wall -Wextra -no-pie
.RECIPEPREFIX = >

all:
> @mkdir ../../build -p
> @mkdir ../../build/application_help -p

> @echo Compiling application_help/main.c ...
        
> @i686-linux-gnu-gcc -c main.c $(CPARAMS) -o ../../build/application_help/main.o 
            
> @echo application_help branch done.
    