CPARAMS=-ffreestanding -O2 -Wall -Wextra
.RECIPEPREFIX = >

all:
> @mkdir ../../build -p
> @mkdir ../../build/include -p

> @echo Compiling include/application_bootscreen ...
        
> @echo include branch done.
    