CPARAMS=-ffreestanding -O2 -Wall -Wextra
.RECIPEPREFIX = >

all:
> @mkdir ../../build -p
> @mkdir ../../build/std -p

> @echo Compiling std/string.c ...
        
> @i686-linux-gnu-gcc -c string.c $(CPARAMS) -o ../../build/std/string.o 
            
> @echo std branch done.
    